name: Snyk Security

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  snyk:
    permissions:
      contents: read
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Snyk CLI
        uses: snyk/actions/setup@806182742461562b67788a64410098c9d9b96adb
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Run Snyk test and save JSON report
        run: |
          set +e
          snyk test --json > snyk-report.json
          echo "Snyk exit code: $?"
          set -e
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Upload JSON report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: snyk-json-report
          path: snyk-report.json
          
          
          
